// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: video_receiving.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ColorBlindnessType int32

const (
	ColorBlindnessType_PROTANOPIA   ColorBlindnessType = 0
	ColorBlindnessType_DEUTERANOPIA ColorBlindnessType = 1
	ColorBlindnessType_TRITANOPIA   ColorBlindnessType = 2
)

// Enum value maps for ColorBlindnessType.
var (
	ColorBlindnessType_name = map[int32]string{
		0: "PROTANOPIA",
		1: "DEUTERANOPIA",
		2: "TRITANOPIA",
	}
	ColorBlindnessType_value = map[string]int32{
		"PROTANOPIA":   0,
		"DEUTERANOPIA": 1,
		"TRITANOPIA":   2,
	}
)

func (x ColorBlindnessType) Enum() *ColorBlindnessType {
	p := new(ColorBlindnessType)
	*p = x
	return p
}

func (x ColorBlindnessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorBlindnessType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_receiving_proto_enumTypes[0].Descriptor()
}

func (ColorBlindnessType) Type() protoreflect.EnumType {
	return &file_video_receiving_proto_enumTypes[0]
}

func (x ColorBlindnessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorBlindnessType.Descriptor instead.
func (ColorBlindnessType) EnumDescriptor() ([]byte, []int) {
	return file_video_receiving_proto_rawDescGZIP(), []int{0}
}

type TaskType int32

const (
	TaskType_NOTHING                      TaskType = 0
	TaskType_EPILEPSY                     TaskType = 1
	TaskType_COLOR_BLINDNESS              TaskType = 2
	TaskType_EPILEPSY_AND_COLOR_BLINDNESS TaskType = 3
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "NOTHING",
		1: "EPILEPSY",
		2: "COLOR_BLINDNESS",
		3: "EPILEPSY_AND_COLOR_BLINDNESS",
	}
	TaskType_value = map[string]int32{
		"NOTHING":                      0,
		"EPILEPSY":                     1,
		"COLOR_BLINDNESS":              2,
		"EPILEPSY_AND_COLOR_BLINDNESS": 3,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_video_receiving_proto_enumTypes[1].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_video_receiving_proto_enumTypes[1]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_video_receiving_proto_rawDescGZIP(), []int{1}
}

type SegmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename           string              `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Number             int64               `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	TaskType           TaskType            `protobuf:"varint,3,opt,name=taskType,proto3,enum=pb.TaskType" json:"taskType,omitempty"`
	ColorBlindnessType *ColorBlindnessType `protobuf:"varint,4,opt,name=colorBlindnessType,proto3,enum=pb.ColorBlindnessType,oneof" json:"colorBlindnessType,omitempty"`
}

func (x *SegmentRequest) Reset() {
	*x = SegmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_receiving_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentRequest) ProtoMessage() {}

func (x *SegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_receiving_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentRequest.ProtoReflect.Descriptor instead.
func (*SegmentRequest) Descriptor() ([]byte, []int) {
	return file_video_receiving_proto_rawDescGZIP(), []int{0}
}

func (x *SegmentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SegmentRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *SegmentRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_NOTHING
}

func (x *SegmentRequest) GetColorBlindnessType() ColorBlindnessType {
	if x != nil && x.ColorBlindnessType != nil {
		return *x.ColorBlindnessType
	}
	return ColorBlindnessType_PROTANOPIA
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Video    []byte `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_receiving_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_video_receiving_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_video_receiving_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Response) GetVideo() []byte {
	if x != nil {
		return x.Video
	}
	return nil
}

type VideoMetadataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *VideoMetadataRequest) Reset() {
	*x = VideoMetadataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_video_receiving_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadataRequest) ProtoMessage() {}

func (x *VideoMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_receiving_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadataRequest.ProtoReflect.Descriptor instead.
func (*VideoMetadataRequest) Descriptor() ([]byte, []int) {
	return file_video_receiving_proto_rawDescGZIP(), []int{2}
}

func (x *VideoMetadataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_video_receiving_proto protoreflect.FileDescriptor

var file_video_receiving_proto_rawDesc = []byte{
	0x0a, 0x15, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xd2, 0x01, 0x0a, 0x0e,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x28, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4b, 0x0a, 0x12,
	0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f,
	0x6c, 0x6f, 0x72, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x12, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x6e, 0x65,
	0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x15, 0x0a, 0x13, 0x5f, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x6e, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x3c, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22, 0x32,
	0x0a, 0x14, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x2a, 0x46, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x42, 0x6c, 0x69, 0x6e, 0x64,
	0x6e, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f, 0x54,
	0x41, 0x4e, 0x4f, 0x50, 0x49, 0x41, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x45, 0x55, 0x54,
	0x45, 0x52, 0x41, 0x4e, 0x4f, 0x50, 0x49, 0x41, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x52,
	0x49, 0x54, 0x41, 0x4e, 0x4f, 0x50, 0x49, 0x41, 0x10, 0x02, 0x2a, 0x5c, 0x0a, 0x08, 0x54, 0x61,
	0x73, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x48, 0x49, 0x4e,
	0x47, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x50, 0x49, 0x4c, 0x45, 0x50, 0x53, 0x59, 0x10,
	0x01, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x49, 0x4e, 0x44,
	0x4e, 0x45, 0x53, 0x53, 0x10, 0x02, 0x12, 0x20, 0x0a, 0x1c, 0x45, 0x50, 0x49, 0x4c, 0x45, 0x50,
	0x53, 0x59, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x43, 0x4f, 0x4c, 0x4f, 0x52, 0x5f, 0x42, 0x4c, 0x49,
	0x4e, 0x44, 0x4e, 0x45, 0x53, 0x53, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_video_receiving_proto_rawDescOnce sync.Once
	file_video_receiving_proto_rawDescData = file_video_receiving_proto_rawDesc
)

func file_video_receiving_proto_rawDescGZIP() []byte {
	file_video_receiving_proto_rawDescOnce.Do(func() {
		file_video_receiving_proto_rawDescData = protoimpl.X.CompressGZIP(file_video_receiving_proto_rawDescData)
	})
	return file_video_receiving_proto_rawDescData
}

var file_video_receiving_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_video_receiving_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_video_receiving_proto_goTypes = []interface{}{
	(ColorBlindnessType)(0),      // 0: pb.ColorBlindnessType
	(TaskType)(0),                // 1: pb.TaskType
	(*SegmentRequest)(nil),       // 2: pb.SegmentRequest
	(*Response)(nil),             // 3: pb.Response
	(*VideoMetadataRequest)(nil), // 4: pb.VideoMetadataRequest
}
var file_video_receiving_proto_depIdxs = []int32{
	1, // 0: pb.SegmentRequest.taskType:type_name -> pb.TaskType
	0, // 1: pb.SegmentRequest.colorBlindnessType:type_name -> pb.ColorBlindnessType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_video_receiving_proto_init() }
func file_video_receiving_proto_init() {
	if File_video_receiving_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_video_receiving_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_receiving_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_video_receiving_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoMetadataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_video_receiving_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_video_receiving_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_receiving_proto_goTypes,
		DependencyIndexes: file_video_receiving_proto_depIdxs,
		EnumInfos:         file_video_receiving_proto_enumTypes,
		MessageInfos:      file_video_receiving_proto_msgTypes,
	}.Build()
	File_video_receiving_proto = out.File
	file_video_receiving_proto_rawDesc = nil
	file_video_receiving_proto_goTypes = nil
	file_video_receiving_proto_depIdxs = nil
}
